build: Fix build error with ell/cleanup.h
This patch fixes the build error due to missing ell/cleanup.h.

./ell/util.h:33:10: fatal error: ell/cleanup.h: No such file or directory
   33 | #include <ell/cleanup.h>
      |          ^~~~~~~~~~~~~~~