shared/shell: Work-around SAT-45980 with wordexp()
Coverity sees a leak when one doesn't exist yet.

Error: RESOURCE_LEAK (CWE-772): [#def23] [important]
bluez-5.77/src/shared/shell.c:534:2: alloc_arg: "parse_args" allocates memory that is stored into "w.we_wordv".
bluez-5.77/src/shared/shell.c:558:3: leaked_storage: Variable "w" going out of scope leaks the storage "w.we_wordv" points to.
556|			"Unable to parse optional command arguments: %s", opt);
557|		free(opt);
558|->		return -EINVAL;
559|	}
560|